name: Next Event Project Platform - GCP Deployment
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{secrets.GCP_WIF_PROVIDER}}
          service_account: ${{secrets.GCP_SA_EMAIL}}
          project_id: ${{GCP_PROJECT_ID}}
